name: WIndows-x64 C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen.sh
      run: ./autogen.sh
    - name: install windows cross compile tools
      run: sudo apt-get install mingw-w64 zip
    - name: configure
      run: ./configure --host=x86_64-w64-mingw32
    - name: make
      run: make
    - name: zip
      run: cd .libs && zip ../admesh.zip admesh.exe libadmesh-1.dll
    - name: upload windows
      uses: actions/upload-artifact@v1
      with:
        name: uploads
        path: admesh.zip
