name: Windows-x64 C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen.sh
      run: ./autogen.sh
    - name: install windows cross compile tools
      run: sudo apt-get install mingw-w64
    - name: configure
      run: ./configure --host=x86_64-w64-mingw32
    - name: make
      run: make
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: upload windows
      uses: actions/upload-artifact@v2
      with:
        name: admesh-${{ steps.vars.outputs.sha_short }}
        path: |
          .libs/admesh.exe
          .libs/libadmesh-1.dll
